### ISSUE TITLE
Error in designer by touch the outer div or by moving the div 

### ISSUE THREAD

**Issue by mcode92** [node-projects/web-component-designer-demo#28]
when i decrease the zoom and i touch or move the design-canvas then it will be not show in the right positon and cannot rest the container.
show the screenshot please.

![image](https://user-images.githubusercontent.com/116522535/197418344-3ae05a92-c621-4914-b779-d01cd0dac0c5.png)
![image](https://user-images.githubusercontent.com/116522535/197418578-4f3dc26e-9d37-41c4-a858-b2c05adf1980.png)

**Comment by jogibear9988** [comment]
I really don't understand what you mean.
Brwser Zoom? Zoom in Designer?
Wich browser?

Could you create a small gif? Or explain better? Don't get what is not workin

I fixed an issue with the docking framework, maybe you meant this?

**Comment by jogibear9988** [comment]
Also browser version?

**Comment by mcode92** [comment]
current chrome version and 106.0.5249.119. and many browser like chrome and brave

**Comment by jogibear9988** [comment]
i still don't get what error you have.

**Comment by jogibear9988** [comment]
now i found it.

you click on the outer canvas.
seems something broke here, i'll fix

**Comment by mcode92** [comment]
Yes when i click the outer canvas .
Thanks

**Comment by jogibear9988** [comment]
should be fixed now
