### ISSUE TITLE
Error by double click on selected element in designer canvas

### ISSUE THREAD

**Issue by mcode92** [node-projects/web-component-designer-demo#37]
If I click on a selected element two or 3 times, then the focus of the element was lost and the border of this element was changed to black and the Maus cursor.
![selected](https://user-images.githubusercontent.com/116522535/204484983-4f9c1bec-1922-406b-bbc2-6a04a9f72197.PNG)

**Comment by mcode92** [comment]
Hallo, have you seen this error ?

**Comment by jogibear9988** [comment]
Yes, if you doubleklick, you get into "contentEdit" mode, wich is there for editing texts.
This is something that I still need to work on and make it better.

If you use the designer in a own project, this can be adjusted by removing the doubleclick extension in your bootstrapper.

**Comment by jogibear9988** [comment]
see here: https://github.com/node-projects/web-component-designer-demo/blob/a5714650840e6a89c4b4032a5d478937fb65c9b3/src/appShell.ts#L12

if doubleklick extensions are set to a empty array, nothing will happen.

but I will work on this extension, and also work on a doubleclick extension for SVGs

**Comment by mcode92** [comment]
Yes is work fine with empty array and this is fine for me thanks :)
