### ISSUE TITLE
demo does not run - syntax error (in firefox)

### ISSUE THREAD

**Issue by JoernT** [node-projects/web-component-designer-demo#7]
Just clicking first demo and gives me an error - a pitty - the project looks indeed very cool.

**Comment by jogibear9988** [comment]
for me the demo works:
![image](https://user-images.githubusercontent.com/364896/171485276-89ae00a2-ae6f-4262-97b0-fdd5ebc61a76.png)

**Comment by jogibear9988** [comment]
I know that at the monent there are many areas not workin good:

- treeview
- enter/leave container
- resize transformed elemnts
- resize to left or top
but we work on this

**Comment by JoernT** [comment]
Ah, i should have noticed. That only show on Firefox. Chrome is working

**Comment by jogibear9988** [comment]
at the moment you need firefox nightly, and enable: javascript.options.experimental.import_assertions

**Comment by jogibear9988** [comment]
but this will be in next firefox (but not yet enabled by default). But it will be enabled in one of the next versions...

**Comment by jogibear9988** [comment]
If we get close to a 1.0 and firefox will still not support import assertions, we always could transpile or remove them

**Comment by jogibear9988** [comment]
https://github.com/tc39/proposal-import-assertions

**Comment by jogibear9988** [comment]
It works now in firefox and in safari technolygy preview
